<?php
/**
 * HD Child Theme - Functions
 *
 * Lightweight child theme that loads inline CSS/JS for quick fixes.
 * No build process required.
 *
 * @package HD-Child
 * @author  HD
 */

defined( 'ABSPATH' ) || exit;

/**
 * Enqueue inline assets (directly loadable, no build required).
 *
 * These files are for emergency patches and quick fixes.
 * Located at theme root: inline.css, inline.js
 *
 * Parent theme handle names (generated by Asset class):
 * - CSS: 'main-css' (from main.scss via pattern: {slug}-{ext})
 * - JS: 'index-js' (from index.js via pattern: {slug}-{ext})
 *
 * @return void
 */
function hd_child_enqueue_assets(): void {
	$themeDir = get_stylesheet_directory();
	$themeUri = get_stylesheet_directory_uri();

	$cssFile = $themeDir . '/inline.css';
	$jsFile  = $themeDir . '/inline.js';

	// Minimum file size to be considered meaningful content.
	$minSize = 300;

	// Parent theme handles (hardcoded - pattern: {slug}-{extension}).
	$parentCssHandle = 'main-css';
	$parentJsHandle  = 'index-js';

	// Enqueue inline.css if it exists and has meaningful content.
	if ( is_file( $cssFile ) && filesize( $cssFile ) > $minSize ) {
		wp_enqueue_style(
			'hd-child-inline',
			$themeUri . '/inline.css',
			[ $parentCssHandle ],
			filemtime( $cssFile )
		);
	}

	// Enqueue inline.js if it exists and has meaningful content.
	if ( is_file( $jsFile ) && filesize( $jsFile ) > $minSize ) {
		wp_enqueue_script(
			'hd-child-inline',
			$themeUri . '/inline.js',
			[ $parentJsHandle ],
			filemtime( $jsFile ),
			true // In footer.
		);
	}
}

add_action( 'wp_enqueue_scripts', 'hd_child_enqueue_assets', 100 );

// --------------------------------------------------
// Custom OG Image for Safe Harbor Station Template
// --------------------------------------------------

add_filter( 'hd_seo_data_filter', 'hd_child_safe_harbor_og_image_filter', 10, 2 );
/**
 * Custom OG Image for safe-harbor-station template.
 *
 * When ?thongdiep=true or ?quoteID=xxx is present, use the quote popup image as og:image.
 *
 * @param array $seoData SEO data array.
 * @param int   $postId  Current post ID.
 *
 * @return array Modified SEO data.
 */
function hd_child_safe_harbor_og_image_filter( array $seoData, int $postId ): array {
	// Check if current template is safe-harbor-station
	if ( ! is_page_template( 'templates/template-page-safe-harbor-station.php' ) ) {
		return $seoData;
	}

	// phpcs:ignore WordPress.Security.NonceVerification.Recommended
	$show_random = isset( $_GET['thongdiep'] ) && $_GET['thongdiep'] === 'true';
	// phpcs:ignore WordPress.Security.NonceVerification.Recommended
	$quote_id_param = isset( $_GET['quoteID'] ) ? absint( $_GET['quoteID'] ) : 0;

	// No params, return original data
	if ( ! $show_random && ! $quote_id_param ) {
		return $seoData;
	}

	$random_quote_id = 0;

	if ( $quote_id_param ) {
		// Check if specific quote ID exists and is a quote post type
		$quote_post = get_post( $quote_id_param );
		if (
			$quote_post
			&& $quote_post->post_type === 'quote'
			&& $quote_post->post_status === 'publish'
		) {
			$random_quote_id = $quote_id_param;
		}
	} elseif ( $show_random ) {
		// Query random quote
		$quote_ids = get_posts(
			[
				'post_type'      => 'quote',
				'posts_per_page' => 40,
				'fields'         => 'ids',
				'no_found_rows'  => true,
				'orderby'        => 'date',
				'order'          => 'DESC',
			]
		);

		$random_quote_id = ! empty( $quote_ids ) ? $quote_ids[ array_rand( $quote_ids ) ] : 0;
	}

	if ( ! $random_quote_id ) {
		return $seoData;
	}

	// Get quote ACF fields
	$quote_acf   = \HD_Helper::getFields( $random_quote_id );
	$quote_popup = $quote_acf['quote_popup'] ?? 0;

	if ( ! $quote_popup ) {
		return $seoData;
	}

	// Get popup image ID
	$popup_image_id = is_array( $quote_popup ) ? ( $quote_popup['id'] ?? $quote_popup['ID'] ?? 0 ) : (int) $quote_popup;

	if ( ! $popup_image_id ) {
		return $seoData;
	}

	// Get image data
	$image_src = wp_get_attachment_image_src( $popup_image_id, 'large' );
	if ( ! $image_src || empty( $image_src[0] ) ) {
		return $seoData;
	}

	// Update SEO data with popup image
	$seoData['image']        = $image_src[0];
	$seoData['image_width']  = (int) $image_src[1];
	$seoData['image_height'] = (int) $image_src[2];
	$seoData['image_alt']    = get_post_meta( $popup_image_id, '_wp_attachment_image_alt', true ) ?: $seoData['title'];
	$seoData['image_type']   = get_post_mime_type( $popup_image_id ) ?: '';

	return $seoData;
}
